{{- if .Values.audit.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-audit
  labels:
    app.kubernetes.io/name: god-clause
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.audit.persistence.size }}
  {{- if .Values.audit.persistence.storageClass }}
  storageClassName: {{ .Values.audit.persistence.storageClass }}
  {{- end }}
{{- end }}
